### ISSUE TITLE
nearlyEqual function incorrect for values on opposite side of 0

### ISSUE THREAD

**Issue by Stannieman** [brazzy/floating-point-gui.de#51]
When we have for example the values -0.000001 and 0.000001, nearlyEqual always returns false for an epsilon < 0.
This is because on the last line "diff / Math.min((absA + absB), Float.MAX_VALUE)" will always return 1.
Some extra care should be taken when a and b are on opposite sides of 0.
I'll try to work something out, but I think that in this case an absolute comparison of diff against epsilon is valid.

**Comment by brazzy** [comment]
I really think this is really a special case where no single implementation will satisfy everyone - for some applications the difference between those two numbers is gigantic and they should absolutely not be considered "nearly equal". I'm actually more concerned about the fact that something like -0.000001 and 0.000001000001 could be considered "nearly equal" when it shouldn't be.

I definitely agree that there needs to be a special different treatment of values on opposite sides of 0, but I'd tend to considere them different by default.

**Comment by brazzy** [comment]
After debugging through my test code (and fixing some errors in the tests), I've realized that they actually cover the case I was worried about and the comparison code effectively does treat numbers on opposite sides of zero the way I want it to.

Basically, the idea is that numbers should only be considered "nearly equal" if the difference between them could conceivably be the result of rounding or base conversion. And that is not really the case for  -0.000001 and 0.000001 because there is still a *huge* range of smaller values between the two due to the scaling the format supports through the exponent.

One could argue that the code is still not right because making the epsilon a paramenter implies that if you choose it large enough, more or less any given values should be considered equal. But I suspect that requirement would cause a lot of problems.

**Comment by Stannieman** [comment]
> Basically, the idea is that numbers should only be considered "nearly equal" if the difference between them could conceivably be the result of rounding or base conversion.

Ok wow you're absolutely right, I was so deep into looking at this that I completely forgot about why we actually need such method at all...

**Comment by brazzy** [comment]
@Stannieman I wouldn't be so sure that rounding errors cannot change the value from 0 to Float.MIN_VALUE, which is the smallest nonzero value a float can hold - that's a very different case than the original -0.000001 and 0.000001 where there are billions of different values in between them.

I also find it a bit hard to believe that there would be much different behaviour between languages and architectures, I'd expect them all to follow the IEEE standard.
