### ISSUE TITLE
Discussion: Would chosing integers with an implicit fixed point really be so bad?

### ISSUE THREAD

**Issue by fer-rum** [brazzy/floating-point-gui.de#53]
I stumbled over your [arguments against using integer with implicit fixed point](https://floating-point-gui.de/formats/integer/) and would like to contribute an alternative view point for your consideration:

## 1 Overflowing Integers
This one might have been a strong counter-argument in the era of 16- or maybe even 32-bit systems. But we have moved on and with 64-bit machines being the default, it is rarely an issue for many applications. Just for visualization, consider [how large 2^64 mm would be](https://www.wolframalpha.com/input/?i=2%5E64+mm)
And then there still is _long_…

## 2 Changing Numbers of Subunits
IMHO this is not an inherent problem of integers as a data type but faulty requirements engineering by the programmer. Either one knows his scope beforehand or falls back to the smallest reasonably possible unit. (Of course you could construct cases like trying to express 1946 [Hungarian Pengö](Hungarian pengő) in US Dollars, even if it made not much sense anymore )

## 3 Rounding Modes
This is also not a problem related to integers per-se. One always has to chose the correct rounding mode depending on application.

## 4 Implicit Decimal Point
For most higher-level languages this is not a problem at all. There are a sufficient amount of constructs to keep the programmer save.
Usually, the larger or more precise numbers are affixed to some kind of unit which can be encapsulated by Objects which keep track of the whole implicit decimal point affair themselves. If in doubt (or lazy) one can always use one of the existing fixed-point libraries.

Cheers,
fer-rum

**Comment by brazzy** [comment]
1. "It probably won't happen with our data" is really not such a great counter to a potential error of *that* magnitude. It's not likely people have stopped using smaller data types.
2. I think you completely missed the point here: Subunits *change in the real world* and your program will have to be able to accommodate those changes. Proper requirements engineering is exactly what should tell you that integers with an implicit fixed points are the *wrong tool*.
3. Yes, you always have to choose the right rounding mode, but if you use integers with implicit fixed points, you also have to *implement* it.
4. Um, yes, that is exactly my point: there are libraries that implement proper decimal types, so *use them* instead of doing your own half-assed implementation that will contain a bunch of bugs and miss a bunch of eventually necessary features that have long since been fixed and handled in those libraries.

**Comment by fer-rum** [comment]
You seem to always consider integers as having an implicit fixed point. 
With this consideration in mind I see where your arguments come from.
My reasoning however is built on the absence of such "conventions".
As a matter of fact, I would abstain from fixed-point crutches as far as possible (except for syntactic sugar to help the programmer and user along). 
When there is a `2` in the code it means `2` not implicitly `0.2`.
The argument hinges on the question 2 _of what_?
This is the point where requirements engineering comes in: 
1. Figure out the lowest resolution of your data.
2. Assuming every calculation is done in this lowest resolution, what is the largest value range you need in this resolution? 
3. From 1) and 2) calculate the minimum amount of bits required to represent the largest value and round up to the next available data type size.

If the data type chosen by the programmer is too small, they did it wrong. Depending on the scope of the problem this can take a considerable amount of time, but this is part of the job and there are no shortcuts around it.
(In Addition: this is why one sanitizes any inputs — to enforce the assumptions made — and why one introduces sanity checks upon the results of computations. )
